package_name = "org.lightningdevkit.ldknode"
cdylib_name = "ldk_node"
kotlin_targets = ["jvm"]
kotlin_target_version = "2.0"
kotlin_multiplatform = false
generate_serializable_types = true
generate_immutable_records = true
