name: Cross-compile and publish bindings for all targets

on:
  push:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref ||  github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: 1.78

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      rust_version: ${{ env.RUST_VERSION }}
    steps:
      - run: echo "setting output variables"

  generate-bindings:
    needs: setup
    uses: ./.github/workflows/gen-bindings-go.yaml
    with:
      rust_version: ${{ needs.setup.outputs.rust_version }}

  build-libraries:
    needs: setup
    uses: ./.github/workflows/build-libraries.yaml
    with:
      rust_version: ${{ needs.setup.outputs.rust_version }}

  publish-ldk-node-go:
    needs:
      - generate-bindings
      - build-libraries
    uses: ./.github/workflows/publish-bindings-go.yaml
    secrets:
      LDK_NODE_GO_DEPLOY_KEY: ${{ secrets.LDK_NODE_GO_DEPLOY_KEY }}
